-- Determine the top 10 artists by number of tracks released

SELECT ar.Name AS Artist,
ar.ArtistId AS ID,
COUNT(t.TrackId) AS Tracks
FROM Artist ar
INNER JOIN Album al
ON al.ArtistId = ar.ArtistId
INNER JOIN Track t
ON al.AlbumId = t.AlbumId
GROUP BY ar.Name,
ar.ArtistId
ORDER BY Tracks DESC
LIMIT 10;

-- Determine the top 10 artists by number of tracks sales

SELECT ar.Name AS Artist,
ar.ArtistId AS ID,
SUM(il.Quantity) AS Sales,
COUNT(DISTINCT t.TrackId) AS Tracks
FROM Artist ar
INNER JOIN Album al
ON al.ArtistId = ar.ArtistId
INNER JOIN Track t
ON al.AlbumId = t.AlbumId
LEFT JOIN InvoiceLine il
ON il.TrackId = t.TrackId
GROUP BY ar.Name,
ar.ArtistId
ORDER BY Sales DESC
LIMIT 10;

-- Determine the top 10 artists by number of unique customers

SELECT *
FROM
(SELECT ar.Name AS Artist,
ar.ArtistId AS ID,
RANK() OVER(ORDER BY COUNT(DISTINCT i.CustomerId) DESC) AS ArtistRank,
COUNT(DISTINCT i.CustomerId) AS Customers
FROM Artist ar
INNER JOIN Album al
ON al.ArtistId = ar.ArtistId
INNER JOIN Track t
ON al.AlbumId = t.AlbumId
INNER JOIN InvoiceLine il
ON il.TrackId = t.TrackId
INNER JOIN Invoice i
ON i.InvoiceId = il.InvoiceId
GROUP BY ar.Name,
ar.ArtistId) r
WHERE r.ArtistRank <= 10
ORDER BY Customers DESC;

-- Determine the total revenue generated by each artist

SELECT ar.Name AS Artist,
ar.ArtistId AS ID,
SUM(il.UnitPrice) AS Revenue,
ROUND(SUM(il.UnitPrice)*100/(SELECT SUM(UnitPrice * Quantity) FROM InvoiceLine), 2) AS RevenuePercentage,
COUNT(DISTINCT t.TrackId) AS Tracks
FROM Artist ar
LEFT JOIN Album al
ON al.ArtistId = ar.ArtistId
LEFT JOIN Track t
ON al.AlbumId = t.AlbumId
LEFT JOIN InvoiceLine il
ON il.TrackId = t.TrackId
GROUP BY ar.Name,
ar.ArtistId
ORDER BY Revenue DESC;

-- Determine the most popular artist in each country

SELECT r.Country,
r.Artist,
r.ID,
r.Sales,
r.Tracks
FROM
(SELECT i.BillingCountry AS Country,
ar.Name AS Artist,
ar.ArtistId AS ID,
SUM(il.Quantity) AS Sales,
(SELECT COUNT(*)
FROM Album a2
INNER JOIN Track t2
ON t2.AlbumId = a2.AlbumId
WHERE a2.ArtistId = ar.ArtistId) AS Tracks,
RANK() OVER (PARTITION BY i.BillingCountry ORDER BY SUM(il.Quantity) DESC) AS ArtistRank
FROM Artist ar
INNER JOIN Album al
ON al.ArtistId = ar.ArtistId
INNER JOIN Track t
ON al.AlbumId = t.AlbumId
INNER JOIN InvoiceLine il
ON il.TrackId = t.TrackId
INNER JOIN Invoice i
ON i.InvoiceId = il.InvoiceId
GROUP BY i.BillingCountry,
ar.Name,
ar.ArtistId) r
WHERE r.ArtistRank = 1
ORDER BY Sales DESC;

-- Determine the artists with the most sales for each year

SELECT r.Year,
r.Artist,
r.ID,
r.Sales,
r.Tracks
FROM
(SELECT strftime('%Y', i.InvoiceDate) AS Year,
ar.Name AS Artist,
ar.ArtistId AS ID,
SUM(il.Quantity) AS Sales,
COUNT(DISTINCT t.TrackId) AS Tracks,
RANK() OVER (PARTITION BY strftime('%Y', i.InvoiceDate) ORDER BY SUM(il.Quantity) DESC) AS ArtistRank
FROM Artist ar
INNER JOIN Album al
ON al.ArtistId = ar.ArtistId
INNER JOIN Track t
ON al.AlbumId = t.AlbumId
INNER JOIN InvoiceLine il
ON il.TrackId = t.TrackId
INNER JOIN Invoice i
ON i.InvoiceId = il.InvoiceId
GROUP BY Year,
ar.Name,
ar.ArtistId) r
WHERE ArtistRank = 1
ORDER BY r.Year DESC;